### ISSUE TITLE
ontime timer

### ISSUE THREAD

**Issue by desertdognl** [bitfocus/companion-module-getontime-ontime#1]
Hey everybody,

I would love to control Ontime (https://www.getontime.no/) with a streamdeck 

Here is a link to the api:
HTTP: https://cpvalente.gitbook.io/ontime/control-and-feedback/http-api
Websocket: https://cpvalente.gitbook.io/ontime/control-and-feedback/websocket-api

I hope that you can help me. If you have any questions don't hesitate and contact me.
Thank you very much.

Best regards

**Comment by cpvalente** [comment]
Hey @josephdadams and @darinpope ,
I have created a PR with initial setup. 

I have yet to understand how feedbacks work since I would like to implement feedback for playback state.
Meanwhile I was hoping for some feedback will follow up with questions in the PR

**Comment by josephdadams** [comment]
@cpvalente I will go ahead and add the module as-is to the betas, and when you have added feedbacks, we can provide an update. If you would like a feedback example, feel free to use any of my modules.

**Comment by cpvalente** [comment]
Perfect, thank you @josephdadams . I will try to figure out the presets and feedback,
Do you have a particular module I could look into?

**Comment by egon1980** [comment]
I don't get I work with companion get a connection failure

**Comment by cpvalente** [comment]
Hi @egon1980 , could you please describe which is your version of Ontime and companion and something about your setup? 
Are you running companion in the same machine as ontime?

**Comment by egon1980** [comment]
running companion 3.0.0, Ontime v2.0.1, macosx Ventura. Both programma's are running on the same machine. No matter what I change on ip I couldn't make a connection. I use the normal setup

**Comment by cpvalente** [comment]
Hi @egon1980 ,

I guess that is the issue.
You should be using the module v2.1.1 with ontime v2.0.0

The module v2.0.1 does not support the newest ontime
