### ISSUE TITLE
ontime behind reverse proxy and subdomain

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion-module-getontime-ontime#12]
Heyo,

We have ontime running on our server now thanks to the great docker image and it is an amazing tool to have running centrally :)

The only thing that doesn't seem to work is the companion connection to a domain name.

Does it generally not accept URLs? or is it a problem because ontime is running behind a reverse proxy? (I have tried ports 80,443 and 4001)

**Comment by kellhogs** [comment]
hey @Fred-DTV is this issue related to the companion module or are you generally not able to access ontime from a domain name?
If so could you move this issue to the [Ontime](https://github.com/cpvalente/ontime/issues) github page?

**Comment by Fred-DTV** [comment]
@kellhogs I've received your answer, even though I can't see it here? To answer your question: We can reach it at the subdomain, just companion doesn't

**Comment by kellhogs** [comment]
jeah sorry i have deleted it as soon as i realised i didn't read your question correctly 😓 

As of now the "Ontime Server Ip" input only accept's ip addresses. I dont see why the connection to an URL shoudn't work. Let me verify this, if it works i'll put an patch out for this.

**Comment by Fred-DTV** [comment]
amazing thanks :)
