### ISSUE TITLE
Companion Connection to GetOnTime Problem: Please Help

### ISSUE THREAD

**Issue by ShaunMarais** [bitfocus/companion-module-getontime-ontime#21]
Hi Everyone!

I'm using Bitfocus 3.0.0-rc1.
I Updated the GetOnTime Module in C:\Program Files\Companion\resources\bundled-modules\getontime-ontime\companion-module-getontime-ontime-2.1.2 from the online [Repository](https://github.com/bitfocus/companion-module-getontime-ontime)

Companion now reads the updated module.
when i enable connection i get the following Status; Unknown Starting...and it doesn't connect.

what am i doing wrong. or rather what steps do i need to follow to get a connection between companion and the OnTime module?

Thank you,
Shaun

**Comment by kellhogs** [comment]
hey @ShaunMarais when you use the module for the first time it default's to the Companion V1 api. Please check that in the module settings the correct ontime version is set.

![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19673098/e229238c-2ac6-430f-a8a4-3fdadd4224f3)

**Comment by ShaunMarais** [comment]
Thank you. Im going to have a look at that. Will keep you posted.

**Comment by egon1980** [comment]
same here I can't edit module settings because it's waiting for connection to start

**Comment by kellhogs** [comment]
Hey @egon1980 thank you for reaching out.

Could you post the logs from the module here?

**Comment by egon1980** [comment]
I can't make a log file " unknown starting "  Waiting for connection to start...
that is the message that I get

**Comment by kellhogs** [comment]
![Screenshot 2023-06-17 165830](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19673098/c8e5be4d-970f-4b3d-8029-f51d57a5315b)

you need to press the little log button and the disable and re enable the module

**Comment by egon1980** [comment]
this is what I get, does nothing<img width="1434" alt="Scherm­afbeelding 2023-06-17 om 17 10 59" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/95760314/945924be-b8ca-41a6-a4ec-154d504e55ea">
<img width="1422" alt="Scherm­afbeelding 2023-06-17 om 17 10 44" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/95760314/b647099d-4ce8-454d-a002-26a765dd810f">

**Comment by kellhogs** [comment]
ok the take a look at the companion logs (top right) pls

**Comment by egon1980** [comment]
<img width="1417" alt="Scherm­afbeelding 2023-06-17 om 17 19 55" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/95760314/292e76e0-b782-4d34-b56a-db6296888b0d">

**Comment by kellhogs** [comment]
ahh you took the code from this repository and copied it in a directory for companionto read right?

**Comment by egon1980** [comment]
i put it here in a directory
<img width="331" alt="Scherm­afbeelding 2023-06-17 om 17 22 43" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/95760314/afbc05c6-6c50-42bc-97df-5075aacf6512">

**Comment by kellhogs** [comment]
Ok the issue here is, that this module is written in typescript. Typescript is a variation of javascript wich needs to be compiled before it can be used. So Companion isn't able to read the Module like that.

This repostiory doesn't contain the compiled files. You would need to compile the code before you can use this module from the repository code.

**Comment by egon1980** [comment]
I tried your latest option and now it's working. Super thx for your support

**Comment by cpvalente** [comment]
Hi @egon1980 , can we close this ticket?

**Comment by egon1980** [comment]
Yes
Met vriendelijke groet,

Egon Mastenbroek


Op za 21 okt 2023 om 11:04 schreef Carlos Valente ***@***.***>

**Comment by ShaunMarais** [comment]
Yes you can close the ticket.

Thank you

Shaun marais
***@***.***
