### ISSUE TITLE
2 or 3 various "Timer Messages" selectable via new companion STEP feature

### ISSUE THREAD

**Issue by iqtreiber** [bitfocus/companion-module-getontime-ontime#26]
One other issue come up today, playing with the „Timer-Messages“.
It works with the one pre-defined at the Ontime-Application-Editor fine. But it is always this "only one" pre-defined.

Is it possible to create various timer-messages through companion steps sending as variable?
Just an idea, to get for example the use case with STEPS in companion

Companion STEP 1:
Short press: 0 sec
Message-Text1: Text 1
Feedback: Show Text 1 at button
No Release

Companion STEP 2:
Short press: 0 sec
Message-Text2: Text 2
Feedback: Show Text 2 at button
No Release

Companion STEP 3:
Short press: 0 sec
Message-Text2: Text 3
Feedback: Show Text 3 at button
No Release

Companion STEP 4:
Short press and hold: 5 sec (just a example)
Show: selected message
Feedback: Show selected Text at button with different button color
Release: hide: select message
(As long as the finger press its shown on stage)

**Comment by alex-Arc** [comment]
it can be done easily with 2 buttons 
[predeftimermsg.zip](https://github.com/bitfocus/companion-module-getontime-ontime/files/12859136/predeftimermsg.zip)

**Comment by iqtreiber** [comment]
Yes, I already have been test the last weeks and it works basically.
It not 100% correct as the buttons are developed as toggle buttons with a checkbox for enable/disable.
To be correct it is either a toggle only or a enable(show) and disable(hide) to be aligned with all other companion modules.

**Comment by cpvalente** [comment]
Hi @iqtreiber , we appreciate your involvement and suggestion.

Currently, improvements to this flow are not part of our roadmap.
