### ISSUE TITLE
No Feedback and all Variables undefined

### ISSUE THREAD

**Issue by herzogmedia** [bitfocus/companion-module-getontime-ontime#29]
Hi there,
I tried to get the companion module working with the latest ontime, but did not have any luck with getting data back from ontime into Companion.

### Used Software

- Ontime v2.9.0
- Companion v3.01+6068
- Ontime Module  v2.1.2

### Expected behaviour
When connecting Companion to Ontime, both control and feedback should be working.

### Observed behaviour
When connecting Companion to Ontime, connection status is green. Controlling ontime works as expected, however there is no feedback on the buttons and all the variables specified give back `undefined`. 
There is no error/warning in the logs of both applications.

**Comment by cpvalente** [comment]
Hi @herzogmedia 
The ontime version you are using depends on the newest module 2.3.0

**Comment by herzogmedia** [comment]
Hi, thanks, did not see there was a new companion module version. Sorry for that and thanks for helping!
