### ISSUE TITLE
BUG: companion feedback shows on all buttons simultaneously

### ISSUE THREAD

**Issue by iqtreiber** [bitfocus/companion-module-getontime-ontime#32]
The companion feedback is NOT correlated to the pressed-button.
Therefore when I press one specific message-button - all buttons got the same feedback - all buttons are red.
In my case 10 messages buttons are red coloured showing they are active at the same time.

Nobody know at this point which is active to release the correct button.
It is a very ugly bug as only the pressed button should show the feedback.

<img width="566" alt="Bildschirmfoto 2023-10-13 um 13 12 44" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/9744544/60ebb728-e72f-4450-8b33-5ea433a22163">

**Comment by cpvalente** [comment]
Hi @iqtreiber,

I am made to be under the impression that this is the expected behaviour for a companion module.
The behaviour you are after should be implemented using the Companion feedback feature.

It is my understanding that, while there is room for improvement, this is the behaviour we expect of this action.
I understand that users leverage several modules in a setup, and having a reasonable expectation of behaviour is important. Perhaps the issue here is on matching expectations rather than implementation...

Do you have a different workflow, perhaps based on another module, which you would like to see? Could you link to a module example?

**Comment by alex-Arc** [comment]
hello @iqtreiber 
a way to work around this is to use the `internal: Variable: Check value`
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/f0a918c3-3520-41da-af24-2753e3714c0c)

**Comment by iqtreiber** [comment]
Hello Alex,

many thanks for your comment on this.
Well, yes & no, this "check of variable" is working consistent at any status.
It does not check if the button is pressed or unpressed (released). Or, do I missing something here?


I have been tested your way and my buttons now always flash red (active) independent of status.
From other companion-modules I have been learned that a dedicated feedback (active / non active) depending if the button is pressed or released need to be implemented.

![Screenshot from 2023-10-26 12-30-54](https://github.com/bitfocus/companion-module-getontime-ontime/assets/9744544/9ffd10c1-7856-4730-9b41-016e60b5089b)

What at least I was expecting and hoping of ontime-companion-module was/is:
1) Button #1 pressed = button #1 feedback change the style (e.g. RED button) all other buttons don't change the style
2) Button #1 released = button #1 feedback don't change the style (keep the default style) all other buttons don't change

>> See disabled feedback configuration (my previous config) the line above of the new feedback with variable:
Current feedback function of ontime-companion-module is button #1 pressed all other 8 buttons change the style to a red coloured button. Now? What button you have been pressed? 

If I do have a misunderstanding to still a configuration I don't know, please let me know.

**Comment by alex-Arc** [comment]
@iqtreiber 
Hmm, I think i see what you want.
You can't really stack feedback's i a nice way. 
What you could do is adding a release action to the button that clears the message.
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/aae25740-162a-462b-bc91-3deb2cd2232e)
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/780af0d9-4435-4785-b53d-f2eb48902f4c)

this should give the following result
![VID_20231026_133223](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/84198ee0-caa6-4ed8-8bfa-59c813caf901)

**Comment by iqtreiber** [comment]
Hi @alex-Arc,

yes this is working and looks like 100% the same as your result.
Many thanks @alex-Arc!!!!

Very similar to a kind of "Push to active" instead of "latch to active" (so called in old companion).
Now they are using steps instead of latch.

OK, well this is working but how we wanna proceed from here?
Is this a kind of short-term work around?

We are using a lot of different companion modules (vMix, X32, Midas, H2R, Newtec, ...)
The all provide the feedback function when just pressed in step1. (without hold on button).
Only Ontime module works different.

BR Stefan

**Comment by alex-Arc** [comment]
That's good to hear @iqtreiber 
could you send a config or an image of how this setup looks like for you in the other modules?

Are you thinking of a feedback that would say something like:
`This message viseble`
then a field for the message and it would only trigger if Timer message is on and the message is == to the field

**Comment by iqtreiber** [comment]
Well, your work around is not a bad solution.
In case of flashing for s short moment a Ontime-Message for the speaker.
It does make sense for me to keep the finger on the button instead of latched button.

However, I apologise that I do not have all my environment with me.
But the Blackmagic ATEM and Behringer X-Air using the buttons like "Toggle / On / Off".
That means the button can be one of these 3 behaviours. (toggle / on / off) >> see a short video.

https://github.com/bitfocus/companion-module-getontime-ontime/assets/9744544/283993ac-0ac6-4714-87d6-58053a8ad811

THE WHOLE ISSUE / USER STORY
Please don't focus only on the press and feedback function.
The complete issue I was looking for is multiple messages as we never have only one message to display.

As this might not be a part of Ontime application >> 
https://github.com/cpvalente/ontime/issues/515

I am thinking to use the companion feature "STEPS" for each predefined message-text one step.
Message-1 (step1), Message-2 (step2), Message-3 (step3) - all at ONE button.
selecting with each press the message no. will feedback the message-text on the button.
by long press (> 2000 ms) display on screen and colouring button red.

This would be the perfect world as only 1 button is needed and adjustable with multiple predefined messages.

I am very interesting about your thoughts and feedback, how you think this would be possible.
thank you, BR Stefan

**Comment by alex-Arc** [comment]
cool
I already have the Toggle / On / Off change pending in an PR #35 

you can somewhat do the on button with the Short release actions
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/3987997b-0b21-432d-b484-8560b40cbe24)
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/b81a4d81-1ef3-4e1b-b41b-83a5a1c82a82)
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/33aa14fa-c9e6-4267-ac69-0d79cd901917)

but for it to be reallye nice companion wold need a long hold action like the short long release

**Comment by alex-Arc** [comment]
@iqtreiber  I got super confused by the # numbers as they link back to issues 
but I think you just meant is as two options right?

It is right that you cant do this right now because the Toggle option is not in the official build right now

**Comment by iqtreiber** [comment]
@alex-Arc, good I am confused too ;-)
No, there is a small-piece solution (toggle, on, off) .... and a beauty-all solution. (step1, step2, ...)
Explained in very details above. 
On which you are working?

**Comment by iqtreiber** [comment]
@alex-Arc, I did not got any response since last week.
Please can you tell what is the current status of above issue?

Last week, a new companion version 3.1.2 was release with a couple of companion-modules.
Unfortunately, nothing from Ontime which were urgent waiting for.
What did happen?

**Comment by alex-Arc** [comment]
@iqtreiber unfortunately I can't push anything to companion and we have to wait for them to come around to look at this module

If it is very urgent you can look into using my branch of this module 
Or contact me here ontime+ac@omnivox.dk

**Comment by cpvalente** [comment]
Hi @iqtreiber , we are trying to cleanup to gain visibility to the changes in v3

Can you please provide feedback as to the implementation so that we can maybe close this ticket?

**Comment by iqtreiber** [comment]
Yes, this issue is solved and the ticket can be closed
