### ISSUE TITLE
BUG: wrong implementation of toggle button

### ISSUE THREAD

**Issue by iqtreiber** [bitfocus/companion-module-getontime-ontime#33]
the current toggle-buttons are developed with parameters enable/disable.
In my opinion this is wrong as toggle means a on/off functionality by each pressing the button.
A parameter inside a toggle feature like enable/disable (on/off) is leading in the wrong operation.

**Comment by cpvalente** [comment]
Hi @iqtreiber, thank you for your suggestion

We looked through this and agree that the naming of the parameter sets incorrect expectations.
From the module development perspective:

> We have the parameter here so users can set the action to on/off like they want and not simply toggle it. Maybe renaming the action to "Set Visibility of timer" etc. would be sufficient. 
Alternatively, we can add a "real" toggle action with no parameter if this would improve the module.

It seems to me that while this is not a bug, it could be improved.
Is there a reasonable expectation that this would work in other ways? Maybe expectations are set by another module?

Or perhaps it is a matter of clarification of expectations?

I look forward to continuing this

**Comment by iqtreiber** [comment]
Hello,

from the experience we have other companion modules provide always two different buttons.
1) toggle button (on/off) via press / release (active as long you hold press)
2) on button via press button (active like a "latch" as long pressing again)
3) off button via press button (off like "de-latched")

A good example in the audio world is the MUTE button. (e.g. Midas X32)
You will press on time MUTE an it has to stay pressed and show red coloured.
Nobody will hold the finger on the MUTE button for time being.

In video companion modules you wanna switch a INPUT via pressing the button once. (no hold)
The active INPUT will be red coloured to see the button is pressed.
Same like overlays in video where you press once.

In my opinion, both kinds of button actions are useful.
Active/Deactive buttons and Toggle buttons.

BR Stefan

**Comment by cpvalente** [comment]
Hi @iqtreiber ,

I am under the impression this has been resolved. Can you please provide some feedback so we can maybe close this ticket?

**Comment by iqtreiber** [comment]
Yes, this issue is solved and the ticket can be closed
