### ISSUE TITLE
"Start event with cue" seems to be missing from the available commands

### ISSUE THREAD

**Issue by tcconway** [bitfocus/companion-module-getontime-ontime#42]
Companion v. 3.1.2

Can't seem to find "Start event with cue" or any way to start an event with a specific cue # (without using "start event dropdown"
When searching for the "start"  command, all I can find is:

- Start event at position
- Start event dropdown
- Start event with given ID
- Start next event
- Start roll mode
- Start selected event

You'd think "Start event dropdown" could work, but when I re-import the show from XLS into Onetime, this gets lost. Yeah, I have a client that likes to make lots of changes...

Is there a way to have "start event with cue" and then I would be able to type the cue number directly? (Note: My cue numbers not integers -- for example "D1-02")

Thanks.

**Comment by alex-Arc** [comment]
Hmmm it should already be there, what module version are you on?

![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/36e0cdc3-c321-4d7a-8a86-cbcc9354c413)
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/64eaaf61-9287-4044-9195-731241edd8d2)

we made a big bump to v3 in December and that has it

![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/840d83f0-a045-4587-b8a8-cc2862b202ab)

**Comment by tcconway** [comment]
Apparently I have v2.3.0 of the module. Doesn't the module get updated with the Companion app (I have v3.1.2)?

**Comment by alex-Arc** [comment]
Ah yes sorry there has not been a companion release since then.
the build process is described here https://github.com/bitfocus/companion-module-base/wiki/Module-packaging
if you can wait a bit Companion 3.2.0 should be right around the corner
or try the 3.2.0- beta it is in there

**Comment by cpvalente** [comment]
Closing as completed
