### ISSUE TITLE
Companion Module Feedback

### ISSUE THREAD

**Issue by texasles** [bitfocus/companion-module-getontime-ontime#47]
I'm sure I'm missing some small thing, but I can't seem to get feedback working in companion. I would love to be able to get companion to display countdown info to my stream deck.

**Comment by alex-Arc** [comment]
Hey @texasles 
what version of companion and ontime are you using?

**Comment by texasles** [comment]
Sorry for the delay. What I'm trying to do is get Millumin time remaining to show up  somewhere in Ontime. Is that possible?

**Comment by alex-Arc** [comment]
you can try to use the external field for this https://ontime.gitbook.io/v2/features/external-data
but you will have to format the data form Millumin somewhere like https://benjamin.kuperberg.fr/chataigne/en

**Comment by texasles** [comment]
Thanks a lot. I haven't been in a place to test it again but will be over the next few days. I will try that suggestion.

Thanks!

Les

—
Les Brown
Founder -Showmakers
 www.Showmakers.app
Freelance Live Event Production
Video Director, TD, EIC
p: 214.690.2648

**Comment by cpvalente** [comment]
Hi @texasles , have you managed to figure out your issues? 
Are we able to close this issue?

**Comment by texasles** [comment]
You can close it. Thanks.

Thanks!

Les

—
Les Brown
Founder -Showmakers
 www.Showmakers.app
Freelance Live Event Production
Video Director, TD, EIC
p: 214.690.2648
