### ISSUE TITLE
"Pause" action is mislabeled as "Load an event"

### ISSUE THREAD

**Issue by lukestein** [bitfocus/companion-module-getontime-ontime#54]
There are two action types labeled as "Load an event." One is actually loading an event, while the other appears to be the "Pause" action.

version 3.3.0+6970 (latest beta)

<img width="735" alt="image" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/44452336/e45636f8-e1eb-4f82-8bcf-76dd988817c1">

**Comment by alex-Arc** [comment]
good catch

**Comment by alex-Arc** [comment]
If you have any ideas for improvements pleas let us know
