### ISSUE TITLE
Companion variable request: Total minutes variable (with – sign if negative)

### ISSUE THREAD

**Issue by lukestein** [bitfocus/companion-module-getontime-ontime#56]
I'm wondering if we could get a variable that exposes `60*hours + minutes` (with the correct sign if negative). This would allow more compact display of timers that rarely go over an hour.

Use case: I would like to be able to display e.g.,
```
 00:11:15 →  11:15
 01:11:15 →  71:15
-00:11:15 → -11:15
-01:11:15 → -71:15
```

Currently we get `$(ontime:time_h)` and `$(ontime:time_m)`, etc. and it's not easy to construct what I'd like. Even just getting the sign (`""` vs `"-"`) exposed would be helpful.

**Comment by lukestein** [comment]
OK, realizing I can achieve what I'd hoped for with a Companion Expression (more cumbersome than I'd hope since Companion doesn't seem to support `trunc`… advice welcome)

```
$(ontime:timer_total_ms) > 0? floor($(ontime:timer_total_ms)/60000) : ceil($(ontime:timer_total_ms)/60000)
```

Feel free to close this request.

**Comment by alex-Arc** [comment]
yeah so `$(ontime:time_h)` would be changed to not contain any sign information 
and adding an new one called `$(ontime:time_sign)` 
how dose that sound to you?

you can use template strings to combine strings https://github.com/bitfocus/companion/blob/main/docs/4_secondary_admin_controls/expressions/expressions.md

 `` `${floor(abs($(ontime:timer_total_ms))/60000)}:${$(ontime:time_s)}` ``

**Comment by lukestein** [comment]
Thanks!

Given I think there's great flexibility with expressions, I think no/minimal changes are necessary.

That said, I think a `time_sign` could be useful if easy.

**Comment by lukestein** [comment]
> if you have a change to get it a test that would be nice you can download a test build here https://github.com/alex-Arc/companion-module-getontime-ontime/actions/runs/9063546493

Would have been happy to give it a try, but I don't actually know how to install a test build

**Comment by alex-Arc** [comment]
Ah :-)
Go to your Companion install location, mine is at `C:\Program Files\Companion`
then into the folder `resources\bundled-modules` here you can find the current module in `getontime-ontime`
replace that with the new one 
(I would pull that out so you can put it back later then)

**Comment by lukestein** [comment]
> Go to your Companion install location, mine is at `C:\Program Files\Companion`
> 
> then into the folder `resources\bundled-modules` here you can find the current module in `getontime-ontime`

Thank you for this! I am running a CompanionPi installation such that it looks like this might involve some `chown` magic I'm not prepared to take on at the very moment. Sorry. 🙇

**Comment by alex-Arc** [comment]
haha OK 😉 
do you have any thoughts about the variable name
they are currently
```
time_h
time_m
time_s
time_n <----???
```

**Comment by lukestein** [comment]
Sorry, is that a sign variable (in which case, `time_sign`?) or a *total minutes including hours* variable (in which case maybe `time_m_inclhours`?)

**Comment by alex-Arc** [comment]
I was thinking `n` for negative but `sign` is properly better
