### ISSUE TITLE
Message visibility toggle only turns messages off (doesn't actually toggle)

### ISSUE THREAD

**Issue by lukestein** [bitfocus/companion-module-getontime-ontime#58]
The Toggle/On/Off visibility of message `>` Toggle action seems to only turn message visibility **off** rather than actually toggle it.

(The On and Off actions seem to work as expected)

Demo:
https://github.com/bitfocus/companion-module-getontime-ontime/assets/44452336/f8f6b2c8-f875-4241-867b-25b8bb0f09f2

**Comment by alex-Arc** [comment]
Yes I see that as well
Have you found other broken toggles?

**Comment by lukestein** [comment]
The only other two toggles (blackout timer and blinking timer) seem to work as expected!

I just quickly tried to test a bunch of the Companion actions (definitely didn't hit every option of every one), and all else seem to work as expected except I can't figure out where the "Lower" or "Public" messages get sent (probably user error, though)
<img width="616" alt="image" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/44452336/d0cbb48c-4c5e-48a9-ba7d-6d0e000ec48e">

**Comment by alex-Arc** [comment]
They have been removed from ontime and will also be gone from companion in the next release
