### ISSUE TITLE
Event indexing 0 or 1 ?

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-module-getontime-ontime#60]
The object `selectedEventIndex` is ofcorece zero based internally
but all out receiving ws API's expect 1 based

Should we +1 to the companion variable `selectedEventIndex`  so that if the user send back this value it will have the same result?

**Comment by alex-Arc** [comment]
@lukestein your input here would also be welcome

**Comment by lukestein** [comment]
Oh that's a good catch. Definitely seems like it should be consistently either 0-based or 1-based.

Is there anywhere in the UI that indices are shown? These seem to be the two places in Companion that they show up, but I realize there may be lots of other ways to hit APIs
<img width="616" alt="image" src="https://github.com/bitfocus/companion-module-getontime-ontime/assets/44452336/2fc00314-3817-4bc2-9893-b826eb23a878">

My gut would have said that if starting from scratch, run all the APIs using the same indexing (0-based?) as the internal implementation. But if all the APIs are already 1-based, then `+1` on the Companion variable seems like a good solution.

**Comment by alex-Arc** [comment]
Yeah the UI is 1-based
![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/19875125/646a2862-ea25-4fdc-8f4a-2efd2295f765)

**Comment by lukestein** [comment]
Oh yeah. Then would def add one to the `selectedEventIndex` Companion variable and make everything external 1-based.
