### ISSUE TITLE
Variables from OnTime

### ISSUE THREAD

**Issue by tcconway** [bitfocus/companion-module-getontime-ontime#7]
Would like to request that the Companion module be able to get variables from Ontime. Things like:

- OnAir/OffAir status
- Current running time
- Current Title and Subtitle
- Current Cue Start, End, Duration

This would be super helpful as we build out our Companion buttons!
Thanks!

**Comment by cpvalente** [comment]
Hi @tcconway , have you got a chance to check the changes in the latest beta?

**Comment by tcconway** [comment]
Hi @cpvalente  -- I'm running companion (3.0.0+5393-beta-c304f676), but don't see the variables @kellhogs mentioned...perhaps I'm running the wrong ver? Would I need to get beta code for this module directly? Thanks all!

**Comment by kellhogs** [comment]
Hey @tcconway,
unfortunately my changes haven't been merged to the official repository yet. So to test the changes you would need to clone my repository (https://github.com/kellhogs/companion-module-getontime-ontime) and run it on a local development instance of companion.

I haven't gotten around to make the module v3 ready yet. Some features are working in v3 and some don't. So it would be best if you test it with the latest stable version of companion.

**Comment by tcconway** [comment]
Thanks @kellhogs for the clarification.

**Comment by josephdadams** [comment]
@kellhogs can this be closed?

**Comment by kellhogs** [comment]
I've implemented the variables as requested by @tcconway 

I would like to get feedback from @tcconway on the implementation before we close this.

**Comment by cpvalente** [comment]
Closing the issue as implemented. No more actionable points here

**Comment by tcconway** [comment]
Thanks for working on this! I do only see "undefined" variable data though.

**Comment by cpvalente** [comment]
Hi @tcconway, great to hear from you

There have been some braking changes in the API recently. With ontime 2.9.0 you need the module version 2.3.0
