### ISSUE TITLE
Adding "title previous" for the the control button "previous"

### ISSUE THREAD

**Issue by iqtreiber** [bitfocus/companion-module-getontime-ontime#71]
Showing the title „now“ and the title „next“ is working great and helpful.
By using the button „Previous“ and „Next“ I would helpful to also get the variable „title-previous“.
Because the this information tells the title-name to know what was previous.

![image](https://github.com/bitfocus/companion-module-getontime-ontime/assets/9744544/dee5bbac-46c9-4b10-b198-a2d9452dfb32)

**Comment by alex-Arc** [comment]
@iqtreiber 
The feature has now been merged, but I can't say when it will be part of a release
Let me know if you know how to install a module manually? Then I can make a build for you
