### ISSUE TITLE
Aux Timer actions not working

### ISSUE THREAD

**Issue by Mboitnott** [bitfocus/companion-module-getontime-ontime#73]
Hello! It appears the action for Start/Stop/Pause Aux timer, is not working. I was using them today and had to switch to generic OSC to control it. I used the /ontime/auxtimer/1/start OSC command and that worked.

**Comment by lukestein** [comment]
Can confirm that Companion aux control doesn't seem to be working, either
- Start/Stop/Pause the aux timer (tried all actions)
- Set the aux timer direction

Module is the version included with Companion 3.3.1 (3.3.1+7001-stable-ee7c3daa)

Ontime version is 3.4.0 alpha

**Comment by Mboitnott** [comment]
@lukestein have you used the generic OSC work around? That would def work for both of those things.

**Comment by lukestein** [comment]
@Mboitnott thanks but I don't need aux control; was just confirming bug and versions for other devs

**Comment by alex-Arc** [comment]
Hey 
It will work whenever the next version of companion releases and includes v4.1.0 of the module https://github.com/bitfocus/companion-module-getontime-ontime/pull/61

It might already be part of the beta or you can add the updated module manually
I have a current build here https://github.com/alex-Arc/companion-module-getontime-ontime/actions/runs/9908118226
