### ISSUE TITLE
Using dynamic graphical progress bar for remain / elapsed timers on a Button

### ISSUE THREAD

**Issue by iqtreiber** [bitfocus/companion-module-getontime-ontime#75]
As new companion module support new library, it would great to use "dynamic progress bar".
External library https://github.com/thedist/companion-module-utils/tree/main

The idea would be to show for remain and elapsed timers a horizontal progress bar.
This could be very similar to all other progress bars inside Ontime views.
In all Ontime views the progress bar run from left to right and change the color close to the end.
Exactly this can be now als be available on a button of companion, showing the Ontime Manager the dynamic progress bar.

**Comment by alex-Arc** [comment]
![image](https://github.com/user-attachments/assets/8fa989be-9c01-4dda-9667-338b941cf18f)
do you think it should be a segmented progress bar like in Ontime or change the colour of the whole bar.
I'm worried that the coloured segments will disappear for long timers 

how about placement, should there perhaps be a placement option?

**Comment by iqtreiber** [comment]
Thanks for brainstorming and discussing the definition!

I do 100% agree with you that a segmented progress bar will be not sufficient and the change of whole bar would be much better. Maybe it is possible to align the color of progress with font color. (=green bar with green font, red bar with red front).

In my opinion is in your example the position at the button the best option. I can not imaging that any other position will be required. But just the scope of this feature will bring a big UX benefit for StreamDeck user.

**Comment by alex-Arc** [comment]
hey

> Maybe it is possible to align the color of progress with font color. (=green bar with green font, red bar with red front).

I unfortunately don't see any way to read the colour of the other elements on the button

> In my opinion is in your example the position at the button the best option. I can not imaging that any other position will be required. But just the scope of this feature will bring a big UX benefit for StreamDeck user.

won't spend anymore time on the placement then

pleas see the linked PR for the current functionality

I have found other modules [ableset](https://github.com/bitfocus/companion-module-leolabs-ableset)
that have the possibility to stretch the progress bar across multiple button to get more resolution, do you see any use for this?

**Comment by iqtreiber** [comment]
Many thanks - just this progress bar will improve UX for StreamDeck users.
I am happy to #76 will a future feature for this companion module.

Sorry, gut I was not able to find any examples of stretch progress bar at „ablese module“.
Can you help where exactly I can find?

**Comment by alex-Arc** [comment]
I can't find a picture of it and cant generate it without having a Ableton license

but it would be something like this
![image](https://github.com/user-attachments/assets/d8587c31-7263-42d1-bfa4-2cb0c3d109ac)

**Comment by alex-Arc** [comment]
it will be merged very soon™️ and should be part of the next companion beta
I don't know when there will be a new stable companion release

**Comment by cpvalente** [comment]
Closing this as it was released in v4.3.0
