### ISSUE TITLE
Lack of WSS Support in "Ontime Server Address" Field

### ISSUE THREAD

**Issue by finn-rm** [bitfocus/companion-module-getontime-ontime#82]
Issue: The "Ontime Server Address" textbox does not allow specifying a wss:// address for secure WebSocket connections when using a reverse proxy with SSL.

Expected Behavior: The field should accept wss:// addresses to enable secure connections through an SSL-configured reverse proxy.

Current Limitation: Only non-secure (ws://) addresses are allowed, preventing secure WebSocket usage behind SSL.

Suggestion: Update the input field to accept wss:// URLs for proper SSL support.

**Comment by alex-Arc** [comment]
Hey
The `Ontime Server Address` textbox expects a http address to connect throng, so you should not write out  `ws://` manually

As for working with SSL through a reverse proxy, this has been merged in #80 and should be available in the next release

**Comment by cpvalente** [comment]
Hi @finn-rm, could you please confirm that this has been resolved in v4.4.0?

**Comment by finn-rm** [comment]
Hi @cpvalente, working as expected. Thanks so much!
