### ISSUE TITLE
Allow loaded event time property to be set to a variable

### ISSUE THREAD

**Issue by admiralchekov** [bitfocus/companion-module-getontime-ontime#85]
I use Ontime to manage recording sessions. For a three hour session the musicians require a 15 minute brake which can be started at any point between 01:15:00 and 01:30:00.

To do this, I have Ontime in roll mode with an event for the first half of the recording session that starts at the scheduled start time for the session and the end time set to the latest time the break must have started by (01:30:00 after the start time). Currently I manually update the end time of the current event if the break starts before 01:30:00 but I would like to be able to press one button in companion to set the end time of the current loaded event to the current time now ($(ontime:clock)).

Thanks in advanced,
Sam

**Comment by alex-Arc** [comment]
This is a good concept
I will look into it when time allows

**Comment by alex-Arc** [comment]
hey @admiralchekov 
would you be able to try out the functionality added in #90 ? To see if it covers your use case
If you cant build it there is a build version here https://github.com/alex-Arc/companion-module-getontime-ontime/actions/runs/12223143470

**Comment by admiralchekov** [comment]
Hi @alex-Arc , sorry for the delay.

This works great, thank you! 

It took me a while to realise that it only works with "End Time (hh:mm:ss)" **and** "End Time" selected in the properties field. With only "End Time (hh:mm:ss)" selected there is no field to input the time and with only "End Time" selected both the fields for inputing "End Time" (as before) and the new "End Time (hh:mm:ss)" (variable enabled field) appear but the new variable enabled field is non functional.
I know this is an early build, I just mention in case it wasn't intedned that way.

Both properties enabled works:
![Image](https://github.com/user-attachments/assets/a5146450-010c-47b4-b64d-c04b50748836)

No input field:
![Image](https://github.com/user-attachments/assets/c71b68fd-b041-4b9c-9a83-f5a8f4ef1516)

Both input fileds but anything in "End Time (hh:mm:ss) does not work:
![Image](https://github.com/user-attachments/assets/0a3b034d-c61f-471c-9717-22fc6cdd4fb9)


Many Thanks,
Sam

**Comment by alex-Arc** [comment]
good catch thank you, it should show up with only `End Time (hh:mm:ss)"` selected
Dose it otherwise make sense?

**Comment by admiralchekov** [comment]
Otherwise perfect, Thank you.

**Comment by alex-Arc** [comment]
Cool, should be available in the next companion release
